version: '3.1'

services:
    
    web-server:
        image: webdev89/phpdebian
        restart: always
        container_name: cisco 
        ports:
          - 8081:80
        environment:
            DB_HOST: db
            DB_DB: cisco_ap
            DB_USER: cisco
            DB_PASS: brestcoredallas89
            MEMCACHED_1: memcached
        volumes:
          - ./VirtualHosts/:/etc/apache2/sites-enabled/
          - ./dist/:/var/www/html
        depends_on:
          - db
        networks:
          - cisco_network
          
    memcached:
        image: memcached
        container_name: MemcachedOne
        restart: always
        networks:
          - cisco_network
    db:
        image: mysql:5.7
        container_name: CiscoDB
        restart: always
        ports:
          - 8082:3306
        environment:
          MYSQL_DATABASE: cisco_ap
          MYSQL_USER: cisco 
          MYSQL_PASSWORD: brestcoredallas89
          MYSQL_ROOT_PASSWORD: root
        volumes:
          - ./app/dump/:/docker-entrypoint-initdb.d
          - MysqlCisco:/var/lib/mysql
        networks:
          - cisco_network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        ports: 
          - 8083:80
        environment:
          PMA_HOST: db
        depends_on:
          - db
        networks:
          - cisco_network
          
networks:
  cisco_network:
    driver: bridge

volumes:
  MysqlCisco: